@startuml
activate SpringBoot
boundary AccountWebController
activate AccountWebController
activate AccountJpaRepositoryAdapter
database CrudRepository
activate CrudRepository

ApiController -> Repository: save(account)
activate Account
Account --> ApiController: account
create AccountResponse
ApiController -> AccountResponse: transform(account)
deactivate Account

activate AccountResponse
AccountResponse --> SpringBoot: response
SpringBoot -> Jackson: mapToJson(response)
Jackson -> Jackson: generate JSON
activate Jackson
Jackson -> AccountResponse: getId()
AccountResponse --> Jackson: 1
Jackson -> AccountResponse: getBalance()
AccountResponse --> Jackson: 20
deactivate Jackson
destroy AccountResponse
Jackson --> SpringBoot: {"id": 123, "balance": 20}
deactivate Jackson

SpringBoot --> client: {"id": 123, "balance": 20}
deactivate ApiController
deactivate SpringBoot
deactivate client
|||
@enduml