@startuml

participant client
activate client
activate SpringBoot
activate ApiController

client -> SpringBoot: GET /api/accounts/123

SpringBoot -> SpringBoot: {id} = 123
SpringBoot -> ApiController: accountInfo("123")
create Account
ApiController -> Account: new Account()
activate Account

ApiController --> SpringBoot: account
SpringBoot -> Jackson: mapToJson(account)
Jackson -> Account: getId (id)
Account -> Jackson: id
Jackson -> Jackson: generate JSON
deactivate Account
Jackson --> SpringBoot: {json}

SpringBoot --> client: {json}
deactivate ApiController
deactivate SpringBoot
deactivate client
@enduml