@startuml
participant client
activate client
activate SpringBoot
activate ApiController
client -> SpringBoot: GET /api/accounts/123

SpringBoot -> SpringBoot: {id} = 123
SpringBoot -> ApiController: accountInfo("123")
create Account
ApiController -> Account: new Account()
activate Account
create AccountResponse
ApiController -> AccountResponse: transform(account)
activate AccountResponse
deactivate Account

ApiController --> SpringBoot: response
SpringBoot -> Jackson: mapToJson(response)
Jackson -> AccountResponse: getId()
AccountResponse --> Jackson: 123
Jackson -> AccountResponse: getBalance()
AccountResponse --> Jackson: 10
Jackson -> Jackson: generate JSON
deactivate AccountResponse
Jackson --> SpringBoot: {"id": 123, "balance": 10}

SpringBoot --> client: {"id": 123, "balance": 10}
deactivate ApiController
deactivate SpringBoot
deactivate client
@enduml