@startuml

class TestDouble as "Test Double"

together {
  class Dummy as "Dummy Object"
  class Fake as "Fake Object"
  class Mock as "Mock Object"
  class Stub as "Test Stub"
  class Spy as "Test Spy"
}

TestDouble <|-- Dummy
TestDouble <|-- Fake
TestDouble <|-- Mock
TestDouble <|-- Stub
TestDouble <|-- Spy

hide circle

@enduml